#!/bin/bash
# worktree-task.sh <name> [JIRA-KEY] [base-ref]
# Create a git worktree + a beads epic named after that worktree, so parallel
# worktrees (e.g. two Claude Code sessions on the same task) share ONE beads DB
# but every worktree's tasks are grouped under its own epic and attributed to
# its own actor.
#
# What it does:
#   1. git worktree add  <repo>-<name>  on branch <name>  (sibling dir)
#   2. bd create epic titled "<name>"  (idempotent: reused if label exists)
#   3. write <worktree>/.beads-worktree.env  (BEADS_ACTOR + BD_WORKTREE_EPIC)
#   4. add .beads-worktree.env to .git/info/exclude (shared by all worktrees)
#   5. print the launch line; output the epic id on the last line (scriptable)
#
# Worktrees auto-share the main repo's beads DB via git-common-dir discovery,
# so no redirect config is needed. Separation is logical: epic + actor.
#
# Examples:
#   ~/.claude/scripts/worktree-task.sh WLB-2223-cc-m3 WLB-2223
#   ~/.claude/scripts/worktree-task.sh WLB-2223-oc-m3 WLB-2223
#
# Then, in the new worktree, before launching the agent:
#   source .beads-worktree.env && claude   # or: grok
# That exports BEADS_ACTOR (per-worktree attribution) and BD_WORKTREE_EPIC,
# which jira-to-bd.sh reads to auto-nest new beads under this worktree's epic.

set -euo pipefail

NAME="${1:-}"
JIRA_KEY="${2:-}"
BASE_REF="${3:-HEAD}"

if [ -z "$NAME" ]; then
  echo "Usage: worktree-task.sh <name> [JIRA-KEY] [base-ref]" >&2
  echo "  <name>      worktree + branch name, e.g. WLB-2223-cc-m3" >&2
  echo "  [JIRA-KEY]  optional, sets epic external-ref" >&2
  echo "  [base-ref]  branch/commit to fork from (default: HEAD)" >&2
  exit 1
fi

bd where >/dev/null 2>&1 || {
  echo "ERROR: no beads workspace here. Run 'bd init' in the repo root first." >&2
  exit 1
}

REPO_ROOT=$(git rev-parse --show-toplevel)
REPO_BASE=$(basename "$REPO_ROOT")
PARENT_DIR=$(dirname "$REPO_ROOT")
WT_PATH="$PARENT_DIR/$REPO_BASE-$NAME"

# 1. Create the worktree (reuse existing branch if present, else branch off base)
if [ -d "$WT_PATH" ]; then
  echo "worktree dir exists, reusing: $WT_PATH" >&2
elif git show-ref --verify --quiet "refs/heads/$NAME"; then
  git worktree add "$WT_PATH" "$NAME" >&2
else
  git worktree add -b "$NAME" "$WT_PATH" "$BASE_REF" >&2
fi

# 2. Create (or reuse) the epic named after the worktree
EPIC_ID=$(bd list --json 2>/dev/null |
  jq -r --arg lbl "worktree:$NAME" \
    '.[] | select((.labels // []) | index($lbl)) | .id' | head -1)

if [ -z "$EPIC_ID" ]; then
  CREATE_ARGS=(--title "$NAME" -t epic --labels "worktree:$NAME" --json)
  [ -n "$JIRA_KEY" ] && CREATE_ARGS+=(--external-ref "$(echo "$JIRA_KEY" | tr '[:lower:]' '[:upper:]')")
  RAW=$(bd create "${CREATE_ARGS[@]}" 2>/dev/null)
  EPIC_ID=$(echo "$RAW" | jq -r '.id // .[0].id // empty' 2>/dev/null || echo "$RAW" | tr -d '"' | head -1)
fi

if [ -z "$EPIC_ID" ]; then
  echo "ERROR: failed to create/find worktree epic for $NAME" >&2
  exit 1
fi

# 3. Write the per-worktree env file
ENV_FILE="$WT_PATH/.beads-worktree.env"
{
  echo "# Auto-generated by worktree-task.sh — source before launching the agent."
  echo "export BEADS_ACTOR=\"$NAME\""
  echo "export BD_WORKTREE_EPIC=\"$EPIC_ID\""
} >"$ENV_FILE"

# 4. Ignore it for all worktrees (info/exclude is shared via git-common-dir)
EXCLUDE="$(git rev-parse --git-common-dir)/info/exclude"
if [ -f "$EXCLUDE" ] && ! grep -qxF ".beads-worktree.env" "$EXCLUDE" 2>/dev/null; then
  echo ".beads-worktree.env" >>"$EXCLUDE"
fi

# 5. Report
echo "worktree: $WT_PATH (branch $NAME)" >&2
echo "epic:     $EPIC_ID  (label worktree:$NAME)" >&2
echo "actor:    $NAME" >&2
echo "next:     cd \"$WT_PATH\" && source .beads-worktree.env && claude   # or: grok" >&2
echo "$EPIC_ID"
